In this notebook we will try to classificate if a particular object is a galaxy, star or quasar based on their spectral charectiristc. This dataset contains 100 000 observations that were gathered by SDSS (Sloan Digital Sky Survey) which is one of the more ambitious and influenctial task of astronomy. It's a project with a great task - creating the map of the sky which began in 2000 year. We will perform a lot of data manipulation such as outlier removing using several techniques and many many others. We will also try to determine which factors can determine what a particular observation is. The last part of this project will be a modeling part. Have a good reading :) 

# 1. Importing the data

In [76]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [77]:
data = pd.read_csv('star_classification.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   obj_ID       100000 non-null  float64
 1   alpha        100000 non-null  float64
 2   delta        100000 non-null  float64
 3   u            100000 non-null  float64
 4   g            100000 non-null  float64
 5   r            100000 non-null  float64
 6   i            100000 non-null  float64
 7   z            100000 non-null  float64
 8   run_ID       100000 non-null  int64  
 9   rerun_ID     100000 non-null  int64  
 10  cam_col      100000 non-null  int64  
 11  field_ID     100000 non-null  int64  
 12  spec_obj_ID  100000 non-null  float64
 13  class        100000 non-null  object 
 14  redshift     100000 non-null  float64
 15  plate        100000 non-null  int64  
 16  MJD          100000 non-null  int64  
 17  fiber_ID     100000 non-null  int64  
dtypes: float64(10), int64(7),

# 2. Feature explanation

Lets explain some of the variables:

* <b>alpha</b> - one of the coordinates defining the position of an object in the celestial sphere. (Since they are shown for epoch J2000, the coordinate shown us the position of an object for date: 2000-01-01 12:00 UTC). It is shown as an hour angle.

* <b>delta</b> - second of the coordinates defining the position of an object in the celestial sphere. (Since they are shown for epoch J2000, the coordinate shown us the position of an object for date: 2000-01-01 12:00 UTC). It is shown in degrees, minutes and seconds. 

* u - ultraviolet filter in the photometric system (shown in magnitudo).

* g - green filter in the photometric system (shown in magnitudo).

* r - red filter in the photometric system (shown in magnitudo).

* i - near infrared filter in the photometric system.

* z - infrared filter in the photometric system.

* run_ID - number to identify a specific scan.

* rerun_ID - number to specify how the image was processed.

* cam_col - camera column to identify the scanline within the run.

* filed_ID - field number to identify the scanline within the run.

* spec_obj_ID - unique ID used for optical spectographic object.

* class - object class.

* redshift - redshift value based on the increase in wavelength.

* plate - plate ID that identifies each plate in SDSS.

* MJD - modified Julian Date indicates when the picture was taken.

* fiber_ID - id that identifies the fiber that pointed the light at the local plane in each observation.




As we see not all of the features must be used for object classification. For now we will stick just with several features such as : u, g, r, i, zk, redshift, MJD, specj_obj_ID.

In [89]:
X_train_expl = X_train_expl[['u', 'g', 'r', 'i', 'z', 'redshift', 'spec_obj_ID', 'MJD']]

In [79]:
class_data

,u,g,r,i,z,redshift,spec_obj_ID,class,MJD
0,23.87882,22.27530,20.39501,19.16573,18.79371,0.634794,6.543777e+18,GALAXY,56354
1,24.77759,22.83188,22.58444,21.16812,21.61427,0.779136,1.176014e+19,GALAXY,58158
2,25.26307,22.66389,20.60976,19.34857,18.94827,0.644195,5.152200e+18,GALAXY,55592
3,22.13682,23.77656,21.61162,20.50454,19.25010,0.932346,1.030107e+19,GALAXY,58039
4,19.43718,17.58028,16.49747,15.97711,15.54461,0.116123,6.891865e+18,GALAXY,56187
...,...,...,...,...,...,...,...,...,...
99995,22.16759,22.97586,21.90404,21.30548,20.73569,0.000000,1.055431e+19,GALAXY,57749
99996,22.69118,22.38628,20.45003,19.75759,19.41526,0.404895,8.586351e+18,GALAXY,56934
99997,21.16916,19.26997,18.20428,17.69034,17.35221,0.143366,3.112008e+18,GALAXY,54535
99998,25.35039,21.63757,19.91386,19.07254,18.62482,0.455040,7.601080e+18,GALAXY,56368


# 3. Splitting the data

In this part we will create train and test dataset, but just for exploratory analysis.

In [80]:
from sklearn.model_selection import train_test_split

class_data['class'] = [0 if value == "GALAXY" else 1 if value == "QSO" else 2 for value in class_data['class']]

X = class_data.drop('class', axis=1)
y = class_data['class']



X_train_expl, X_test_expl, y_train_expl, y_test_expl = train_test_split(X, y, test_size=0.35, random_state=32)

/var/folders/rd/z4g97_m5135b3yksvpxnxw1m0000gn/T/ipykernel_3019/1630653737.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  class_data['class'] = [0 if value == "GALAXY" else 1 if value == "QSO" else 2 for value in class_data['class']]


# 4. Data Exploration

## 4.1 Checking descriptive statistics.

In [81]:
X_train_expl.drop('spec_obj_ID', axis=1).describe()

,u,g,r,i,z,redshift,MJD
count,65000.000000,65000.000000,65000.000000,65000.000000,65000.000000,65000.000000,65000.000000
mean,21.916873,20.470751,19.640217,19.079286,18.610571,0.574085,55578.807415
std,39.370115,39.353093,1.857985,1.759607,39.332702,0.728168,1815.199290
min,-9999.000000,-9999.000000,10.068540,10.008650,-9999.000000,-0.004713,51608.000000
25%,20.349125,18.956345,18.116867,17.720872,17.445032,0.055721,54230.000000
50%,22.174765,21.092955,20.117060,19.399605,19.002025,0.420521,55866.000000
75%,23.673455,22.121110,21.047262,20.394020,19.918708,0.702435,56777.000000
max,32.781390,31.602240,29.374110,30.250090,29.383740,7.011245,58932.000000


As we see there's some strange min values in several columns. Value -9999 usually mean two things:

* 1. Particular object was not visible in this particular light,

* 2. There was some error in data preprocessing stage. 

For this notebook we will delete all of the records in which particular columns have value -9999.000 .

In [85]:
X_train_expl = X_train_expl[(X_train_expl != -9999.).all(axis=1)]

In [86]:
X_train_expl.describe()

,u,g,r,i,z,redshift,spec_obj_ID,MJD
count,64999.000000,64999.000000,64999.000000,64999.000000,64999.000000,64999.000000,6.499900e+04,64999.000000
mean,22.071043,20.624899,19.640240,19.079302,18.764690,0.574094,5.770335e+18,55578.816782
std,2.248174,2.039641,1.857991,1.759616,1.768907,0.728170,3.333130e+18,1815.211683
min,10.996230,10.498200,10.068540,10.008650,10.225510,-0.004713,2.995801e+17,51608.000000
25%,20.349225,18.956530,18.116865,17.720845,17.445130,0.055728,2.825000e+18,54230.000000
50%,22.174790,21.093050,20.117070,19.399610,19.002040,0.420537,5.602747e+18,55866.000000
75%,23.673480,22.121120,21.047275,20.394070,19.918725,0.702442,8.331791e+18,56777.000000
max,32.781390,31.602240,29.374110,30.250090,29.383740,7.011245,1.412694e+19,58932.000000


## 4.2 Dealing with Outliers


Outliers can highly impact model performance. Since I assume, that our data can be well clustered, we can use `LocalOutlierFactor` to determine which points in our dataframe are considered as outliers. LocalOutlierFactor works in several steps:

* 1. Calculating the neighbour density - for each point we are calculating the neighbour density. This means, how much other points are in within particular neighbour.

* 2. Calculating "local rechability density" (LRD) - calcualting the local distance for each point to their nearest neighbourhood.

* 3. Calculating the "LOF" coefficient - for each point we are calculating local density of that point to the average local density of their neighbours.

If LOF is equal to -1 (in scikit learn terms) particular observation can be considered as an outlier.

In [97]:
from sklearn.neighbors import LocalOutlierFactor

LOF = LocalOutlierFactor()
predictions = LOF.fit_predict(X_train_expl)
X_train_expl['out'] = predictions
print(f"Number of outliers: {len(X_train_expl[predictions == -1])}")



Number of outliers: 8110


Now let's try to visualise the outliers.

## 4.2 Checking balance of the classes.

As we see our classes are a little bit inbalanced. We can perform `SMOTE` (Symethric Minority Over-Sampling Technique) in order to rebalance the data. SMOTE algorithm will generate synthetic samples into our data, without the need of copying the real data. How does SMOTE work?

* 1. Picking an centroid: For each of the sample in minority class, SMOTE will pick a point from which the distance to n samples (for example 5) is the closest.

* 2. Creating synthetic samples: Based on the differences between the samples and their neighbors new samples are generated. Those new samples are placed in the staright line between the neighbor and the sample.


In [84]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(
    k_neighbors=7,
    n_jobs=-1,
    random_state=42
)

